name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # sadece main branch'e push olunca çalışır

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy aiom-site \
            --source . \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
